version: '3.8'
services:
  thingsboard-db:
    image: postgres:latest
    container_name: thingsboard-db
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: tb_user
      POSTGRES_PASSWORD: tb_password
    volumes:
      - thingsboard-db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  thingsboard-db-data:
