version: '3.8'

services:
  # # ThingsBoard PostgreSQL Database
  # thingsboard-db:
  #   image: postgres:latest
  #   container_name: thingsboard-db
  #   environment:
  #     POSTGRES_DB: thingsboard
  #     POSTGRES_USER: tb_user
  #     POSTGRES_PASSWORD: tb_password
  #   volumes:
  #     - thingsboard-db-data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # # ThingsBoard Service
  # thingsboard:
  #   image: thingsboard/tb-postgres
  #   container_name: thingsboard
  #   environment:
  #     TB_DB_HOST: thingsboard-db
  #     TB_DB_USER: tb_user
  #     TB_DB_PASSWORD: tb_password
  #     TB_QUEUE_TYPE: rdb
  #   depends_on:
  #     - thingsboard-db
  #   ports:
  #     - "8580:8580"  # ThingsBoard Web UI
  #   restart: unless-stopped

  # Keycloak Service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8081"  # Keycloak Web UI
    restart: unless-stopped

  # RabbitMQ Service (for messaging)
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management Console
      - "5672:5672"    # RabbitMQ Message Queue
    restart: unless-stopped

  # MinIO Service (object storage)
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: your-access-key
      MINIO_SECRET_KEY: your-secret-key
    ports:
      - "9000:9000"  # MinIO Web UI
      - "9001:9001"  # MinIO Console
    command: server /data
    volumes:
      - minio-data:/data
    restart: unless-stopped

  # Node-RED Service
  nodered:
    image: nodered/node-red
    container_name: nodered
    environment:
      - FOLDER=./data
    ports:
      - "8990:8990"  # Node-RED Web UI
    restart: unless-stopped

volumes:
  thingsboard-db-data:
  minio-data:
