apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: cloud-platform
spec:
  ports:
  - port: 1880
    targetPort: 1880
    protocol: TCP
  selector:
    app: nodered
  type: ClusterIP  