apiVersion: v1
kind: Service
metadata:
  name: thingsboard-postgres
  namespace: cloud-platform
spec:
  selector:
    app: thingsboard
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
