version: '3.8'

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    environment:
      - FOLDER=./data
    ports:
      - "8990:8990"  # Node-RED Web UI
    restart: unless-stopped
