apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: cloud-platform
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /home/axilleas/Documents/Projects/CloudPlatformESP/k8s/pv/minio
