apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: cloud-platform
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: web
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    app: minio
  type: ClusterIP
