apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: cloud-platform
spec:
  type: NodePort  # Enables both ClusterIP and NodePort
  externalTrafficPolicy: Local  # Ensures correct routing of external traffic
  selector:
    app: minio
  ports:
    - name: web
      port: 9000         # ClusterIP access
      targetPort: 9000   # MinIO container port
      nodePort: 30090    # External NodePort (for ESP32)
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30091    # External NodePort (for MinIO Console)
