apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: cloud-platform
spec:
  ports:
  - port: 15672       # Management Console
    targetPort: 15672
    name: management
  - port: 5672        # Message Queue
    targetPort: 5672
    name: queue
  selector:
    app: rabbitmq
  clusterIP: None  # This ensures the Service works with the StatefulSet
