apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: cloud-platform
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80        # Internal Cluster Port
      targetPort: 3000 # Grafana Container Port
      nodePort: 30000  # External Port for Access
