apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: cloud-platform
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: # Use hostPath for local development; use a cloud storage class in production
    path: /home/niroth36/Documents/Projects/CloudPlatformESP/k8s/pv/grafana
