version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LISTENERS_HTTP=8080
    ports:
      - "8090:8080"  # Mapping internal port 8080 to external 8090
    command:
      - start-dev  # Use start-dev to avoid HTTPS and run in development mode
    restart: unless-stopped
