version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management Console
      - "5672:5672"    # RabbitMQ Message Queue
    restart: unless-stopped