version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: your-access-key
      MINIO_SECRET_KEY: your-secret-key
    ports:
      - "9000:9000"  # MinIO Web UI
      - "9001:9001"  # MinIO Console
    volumes:
      - minio-data:/data
    command: server /data
    restart: unless-stopped

volumes:
  minio-data:
